<a href="https://colab.research.google.com/github/Carmodann1311/proyectos-AP.M/blob/main/Logistica_regresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

equipos = {
    "America": [17, 12, 14, 37, 14, 23, 1],
    "Monterrey": [33, 17, 10, 4, 3, 27, 15, 12, 1],
    "Tigres": [30, 17, 8, 3, 6, 32, 18, 14, 1],
    "Pumas": [28, 17, 8, 5, 4, 27, 18, 9, 1],
    "Chivas": [27, 17, 8, 6, 3, 22, 22, 0, 1],
    "Puebla": [25, 17, 7, 6, 4, 24, 25, -1, 1],
    "San luis": [23, 17, 7, 8, 2, 31, 26, 5, 0],
    "Leon": [23, 17, 6, 6, 5, 23, 22, 1, 0],
    "Santos": [23, 17, 7, 8, 2, 31, 34, -3, 0],
    "Mazatlan": [22, 17, 6, 7, 4, 25, 27, -2, 0],
    "Pachuca": [22, 17, 5, 5, 7, 16, 27, -11, 0],
    "Toluca": [21, 17, 5, 6, 6, 23, 19, 4, 0],
    "TIjuana": [20, 17, 6, 9, 2, 23, 26, -3, 0],
    "Queretaro": [19, 17, 5, 8, 4, 18, 29, -11, 0],
    "Juarez": [18, 17, 5, 9, 3, 24, 34, -10, 0],
    "Cruz azul": [17, 17, 5, 10, 2, 21, 29, -8, 0],
    "Atlas": [17, 17, 4, 8, 5, 14, 24, -10, 0],
    "Necaxa": [15, 17, 3, 8, 6, 18, 27, -9, 0]
}

nombres = []

clasificacion = []

goles = []

for equipo, datos in equipos.items():
    nombres.append(equipo)
    clasificacion.append(datos[-1])
    goles.append(datos[-3:-1])

clasificacion = np.array(clasificacion)
goles = np.array(goles)

print(clasificacion)
print(goles)

[1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
[[ 14  23]
 [ 15  12]
 [ 18  14]
 [ 18   9]
 [ 22   0]
 [ 25  -1]
 [ 26   5]
 [ 22   1]
 [ 34  -3]
 [ 27  -2]
 [ 27 -11]
 [ 19   4]
 [ 26  -3]
 [ 29 -11]
 [ 34 -10]
 [ 29  -8]
 [ 24 -10]
 [ 27  -9]]


In [ ]:
from sklearn.linear_model import LogisticRegression

modelo = LogisticRegression()

modelo.fit(goles, clasificacion)

intercepto = modelo.intercept_
coeficientes = modelo.coef_

print(intercepto)
print(coeficientes)

[4.37533861]
[[-0.22903146  0.16123273]]


In [ ]:
probabilidades = modelo.predict_proba(goles)

print(probabilidades)

[[0.00756033 0.99243967]
 [0.05342055 0.94657945]
 [0.07515799 0.92484201]
 [0.1539609  0.8460391 ]
 [0.66001332 0.33998668]
 [0.81931015 0.18068985]
 [0.68423772 0.31576228]
 [0.62295761 0.37704239]
 [0.98007061 0.01992939]
 [0.89387766 0.10612234]
 [0.97293487 0.02706513]
 [0.33879432 0.66120568]
 [0.88727239 0.11272761]
 [0.98270912 0.01729088]
 [0.99346521 0.00653479]
 [0.97225158 0.02774842]
 [0.93898867 0.06101133]
 [0.96301674 0.03698326]]
